version: "3.9"

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD:-root}
    ports:
      - "3306:3306"
    command: >-
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

  users-service:
    image: "${REGISTRY_PREFIX:-epem}/users-service:${IMAGE_TAG:-latest}"
    build:
      context: .
      args:
        PACKAGE: "@epem/users-service"
    command: pnpm --filter @epem/users-service start:prod
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          node -e "require('http').get('http://localhost:3020/api/health',r=>process.exit(r.statusCode>=200&&r.statusCode<300?0:1)).on('error',()=>process.exit(1))"
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      NODE_ENV: production
      USERS_SERVICE_PORT: 3020
      USERS_SERVICE_DATABASE_URL: ${USERS_SERVICE_DATABASE_URL:-mysql://root:${DATABASE_PASSWORD:-root}@mysql:3306/epem_users}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      ACCESS_TOKEN_TTL: ${ACCESS_TOKEN_TTL:-900}
      REFRESH_TOKEN_TTL: ${REFRESH_TOKEN_TTL:-604800}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost}
      SERVICE_NAME: users-service
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - epem

  patients-service:
    image: "${REGISTRY_PREFIX:-epem}/patients-service:${IMAGE_TAG:-latest}"
    build:
      context: .
      args:
        PACKAGE: "@epem/patients-service"
    command: pnpm --filter @epem/patients-service start:prod
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          node -e "require('http').get('http://localhost:3010/health',r=>process.exit(r.statusCode>=200&&r.statusCode<300?0:1)).on('error',()=>process.exit(1))"
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      NODE_ENV: production
      PATIENTS_SERVICE_PORT: 3010
      PATIENTS_SERVICE_DATABASE_URL: ${PATIENTS_SERVICE_DATABASE_URL:-mysql://root:${DATABASE_PASSWORD:-root}@mysql:3306/epem}
      BILLING_SERVICE_URL: ${BILLING_SERVICE_URL:-http://billing-service:3040}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost}
      SERVICE_NAME: patients-service
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - epem

  catalog-service:
    image: "${REGISTRY_PREFIX:-epem}/catalog-service:${IMAGE_TAG:-latest}"
    build:
      context: .
      args:
        PACKAGE: "@epem/catalog-service"
    command: pnpm --filter @epem/catalog-service start:prod
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          node -e "require('http').get('http://localhost:3030/health',r=>process.exit(r.statusCode>=200&&r.statusCode<300?0:1)).on('error',()=>process.exit(1))"
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      NODE_ENV: production
      CATALOG_SERVICE_PORT: 3030
      CATALOG_SERVICE_DATABASE_URL: ${CATALOG_SERVICE_DATABASE_URL:-mysql://root:${DATABASE_PASSWORD:-root}@mysql:3306/epem_catalog}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost}
      SERVICE_NAME: catalog-service
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - epem

  billing-service:
    image: "${REGISTRY_PREFIX:-epem}/billing-service:${IMAGE_TAG:-latest}"
    build:
      context: .
      args:
        PACKAGE: "@epem/billing-service"
    command: pnpm --filter @epem/billing-service start:prod
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          node -e "require('http').get('http://localhost:3040/health',r=>process.exit(r.statusCode>=200&&r.statusCode<300?0:1)).on('error',()=>process.exit(1))"
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      NODE_ENV: production
      BILLING_SERVICE_PORT: 3040
      BILLING_SERVICE_DATABASE_URL: ${BILLING_SERVICE_DATABASE_URL:-mysql://root:${DATABASE_PASSWORD:-root}@mysql:3306/epem_billing}
      PATIENTS_SERVICE_URL: ${PATIENTS_SERVICE_URL:-http://patients-service:3010}
      CATALOG_SERVICE_URL: ${CATALOG_SERVICE_URL:-http://catalog-service:3030}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost}
      SERVICE_NAME: billing-service
    depends_on:
      mysql:
        condition: service_healthy
      patients-service:
        condition: service_healthy
      catalog-service:
        condition: service_healthy
    networks:
      - epem

  api-gateway:
    image: "${REGISTRY_PREFIX:-epem}/api-gateway:${IMAGE_TAG:-latest}"
    build:
      context: .
      args:
        PACKAGE: "@epem/api-gateway"
    command: pnpm --filter @epem/api-gateway start:prod
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          node -e "require('http').get('http://localhost:4000/health',r=>process.exit(r.statusCode>=200&&r.statusCode<300?0:1)).on('error',()=>process.exit(1))"
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      NODE_ENV: production
      API_GATEWAY_PORT: 4000
      USERS_SERVICE_URL: ${USERS_SERVICE_URL:-http://users-service:3020/api}
      PATIENTS_SERVICE_URL: ${PATIENTS_SERVICE_URL:-http://patients-service:3010}
      CATALOG_SERVICE_URL: ${CATALOG_SERVICE_URL:-http://catalog-service:3030}
      BILLING_SERVICE_URL: ${BILLING_SERVICE_URL:-http://billing-service:3040}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost}
      DEFAULT_ORIGIN: ${DEFAULT_ORIGIN:-http://localhost}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN:-}
      COOKIE_SECURE: ${COOKIE_SECURE:-false}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      ACCESS_TOKEN_TTL: ${ACCESS_TOKEN_TTL:-900}
      REFRESH_TOKEN_TTL: ${REFRESH_TOKEN_TTL:-604800}
      SERVICE_NAME: api-gateway
    depends_on:
      users-service:
        condition: service_healthy
      patients-service:
        condition: service_healthy
      catalog-service:
        condition: service_healthy
      billing-service:
        condition: service_healthy
    networks:
      - epem

  web:
    image: "${REGISTRY_PREFIX:-epem}/web:${IMAGE_TAG:-latest}"
    build:
      context: .
      args:
        PACKAGE: "@epem/web"
    command: pnpm --filter @epem/web start
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8080}
      API_GATEWAY_URL: ${API_GATEWAY_URL:-http://api-gateway:4000}
    depends_on:
      api-gateway:
        condition: service_healthy
    networks:
      - epem

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      web:
        condition: service_started
      api-gateway:
        condition: service_healthy
    ports:
      - "8080:80"
    volumes:
      - ./ops/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - epem

  prometheus:
    image: prom/prometheus:latest
    depends_on:
      api-gateway:
        condition: service_healthy
      patients-service:
        condition: service_healthy
      catalog-service:
        condition: service_healthy
      billing-service:
        condition: service_healthy
      users-service:
        condition: service_healthy
    volumes:
      - ./ops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./ops/prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
    ports:
      - "9090:9090"
    networks:
      - epem

  grafana:
    image: grafana/grafana-oss:10.4.2
    depends_on:
      prometheus:
        condition: service_started
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD:-admin}
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
    ports:
      - "3001:3000"
    volumes:
      - ./ops/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./ops/grafana:/var/lib/grafana/dashboards:ro
    networks:
      - epem

volumes:
  mysql_data:

networks:
  epem:
    driver: bridge
