version: '3.9'

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD:-root}
    ports:
      - '3306:3306'
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql

  users-service:
    build:
      context: .
      args:
        PACKAGE: @epem/users-service
    command: pnpm --filter @epem/users-service start:prod
    environment:
      NODE_ENV: production
      USERS_SERVICE_PORT: 3020
      USERS_SERVICE_DATABASE_URL: ${USERS_SERVICE_DATABASE_URL:-mysql://root:${DATABASE_PASSWORD:-root}@mysql:3306/epem_users}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      ACCESS_TOKEN_TTL: ${ACCESS_TOKEN_TTL:-900}
      REFRESH_TOKEN_TTL: ${REFRESH_TOKEN_TTL:-604800}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost}
      SERVICE_NAME: users-service
    depends_on:
      - mysql
    networks:
      - epem

  patients-service:
    build:
      context: .
      args:
        PACKAGE: @epem/patients-service
    command: pnpm --filter @epem/patients-service start:prod
    environment:
      NODE_ENV: production
      PATIENTS_SERVICE_PORT: 3010
      PATIENTS_SERVICE_DATABASE_URL: ${PATIENTS_SERVICE_DATABASE_URL:-mysql://root:${DATABASE_PASSWORD:-root}@mysql:3306/epem}
      BILLING_SERVICE_URL: ${BILLING_SERVICE_URL:-http://billing-service:3040}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost}
      SERVICE_NAME: patients-service
    depends_on:
      - mysql
    networks:
      - epem

  catalog-service:
    build:
      context: .
      args:
        PACKAGE: @epem/catalog-service
    command: pnpm --filter @epem/catalog-service start:prod
    environment:
      NODE_ENV: production
      CATALOG_SERVICE_PORT: 3030
      CATALOG_SERVICE_DATABASE_URL: ${CATALOG_SERVICE_DATABASE_URL:-mysql://root:${DATABASE_PASSWORD:-root}@mysql:3306/epem_catalog}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost}
      SERVICE_NAME: catalog-service
    depends_on:
      - mysql
    networks:
      - epem

  billing-service:
    build:
      context: .
      args:
        PACKAGE: @epem/billing-service
    command: pnpm --filter @epem/billing-service start:prod
    environment:
      NODE_ENV: production
      BILLING_SERVICE_PORT: 3040
      BILLING_SERVICE_DATABASE_URL: ${BILLING_SERVICE_DATABASE_URL:-mysql://root:${DATABASE_PASSWORD:-root}@mysql:3306/epem_billing}
      PATIENTS_SERVICE_URL: ${PATIENTS_SERVICE_URL:-http://patients-service:3010}
      CATALOG_SERVICE_URL: ${CATALOG_SERVICE_URL:-http://catalog-service:3030}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost}
      SERVICE_NAME: billing-service
    depends_on:
      - mysql
      - patients-service
      - catalog-service
    networks:
      - epem

  api-gateway:
    build:
      context: .
      args:
        PACKAGE: @epem/api-gateway
    command: pnpm --filter @epem/api-gateway start:prod
    environment:
      NODE_ENV: production
      API_GATEWAY_PORT: 4000
      USERS_SERVICE_URL: ${USERS_SERVICE_URL:-http://users-service:3020/api}
      PATIENTS_SERVICE_URL: ${PATIENTS_SERVICE_URL:-http://patients-service:3010}
      CATALOG_SERVICE_URL: ${CATALOG_SERVICE_URL:-http://catalog-service:3030}
      BILLING_SERVICE_URL: ${BILLING_SERVICE_URL:-http://billing-service:3040}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost}
      DEFAULT_ORIGIN: ${DEFAULT_ORIGIN:-http://localhost}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN:-}
      COOKIE_SECURE: ${COOKIE_SECURE:-false}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      ACCESS_TOKEN_TTL: ${ACCESS_TOKEN_TTL:-900}
      REFRESH_TOKEN_TTL: ${REFRESH_TOKEN_TTL:-604800}
      SERVICE_NAME: api-gateway
    depends_on:
      - users-service
      - patients-service
      - catalog-service
      - billing-service
    networks:
      - epem

  web:
    build:
      context: .
      args:
        PACKAGE: @epem/web
    command: pnpm --filter @epem/web start
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8080}
      API_GATEWAY_URL: ${API_GATEWAY_URL:-http://api-gateway:4000}
    depends_on:
      - api-gateway
    networks:
      - epem

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - web
      - api-gateway
    ports:
      - '8080:80'
    volumes:
      - ./ops/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - epem

  prometheus:
    image: prom/prometheus:latest
    depends_on:
      - api-gateway
      - patients-service
      - catalog-service
      - billing-service
      - users-service
    volumes:
      - ./ops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - '9090:9090'
    networks:
      - epem

  grafana:
    image: grafana/grafana:10.4.0
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD:-admin}
    ports:
      - '3001:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - epem

volumes:
  mysql_data:
  grafana_data:

networks:
  epem:
    driver: bridge
